### ISSUE TITLE
Tooltitude causes vscode to stutter and slow

### ISSUE THREAD

**Issue by vamshiaruru32** [tooltitude/support#31]
Type: <b>Bug</b>

Recently I have noticed that my VSCode was being extremely laggy and slow. Scrolling a go file with more than 500 lines causes noticeable frame drops and almost makes VSCode unusable. I used extension bisect to figure out what's happening, and turns out it is because of tooltitude. I love the functionality of the extension, but the performance hit is noticeable.

Extension version: 0.46.2
VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|/Users/vamshiaruru/tectonic/avalon --crash-reporter-id 7b32afc3-053b-4bfc-8bb5-1e6a597c14f3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2:30926735
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by tooltitude-support** [comment]
Thank you for your feedback. I am sorry that you have such a bad experience. 500 lines of code isn't the size where it should be slow, I regularly test with files which are much larger, and didn't notice any problems with them.

My hypothesis is that something is wrong with the handling of the file, i.e. panic happens during file check, or code lens production, and it is being repeated again and again.

Could you go to the tooltitude output like on the screenshot and see what's happening there. It shows requests which are being performed and how long they take. In normal situation, nothing should happen, i.e. the files are checked, code lenses produced, but in your case something else is going on. Could you take a look there? (Please don't share output here since it might contain public data)

<img width="1078" alt="Screenshot 2023-12-21 at 5 52 39 PM" src="https://github.com/tooltitude/support/assets/123904466/4bc33d8f-1667-4661-bbdd-8f571c99d0e0">

**Comment by tooltitude-support** [comment]
Also, consider joining our discord: https://discord.com/invite/f9MHBXsVwr If you have some info to share, please DM me there (I am the moderator of the channel, so it's easy to find me)

**Comment by tooltitude-support** [comment]
There were no reports about this for over a month, so I am closing this as obsolete. Please, reopen this issue if it happens again.

**Comment by tooltitude-support** [comment]
@vamshiaruru32 If you are still using Tooltitude, and have it, you could help us find and fix it using the instruction here: https://github.com/tooltitude/support/issues/33#issuecomment-1961468712
