### ISSUE TITLE
Debugging an individual table-driven test always runs all tests in the table

### ISSUE THREAD

**Issue by unguiculus** [tooltitude/support#46]
Tooltitude Version: v0.103.2

OS Version: MacOS 14.6.1

VS Code Version: 1.95.3

Go Version: 1.23.3

What did you try to do?

Debug an individual table-driven test case using the debugging code lens. This always runs all test cases of the test function instead of just the specific one that was selected.

**Comment by tooltitude-support** [comment]
@unguiculus Thank you for your feedback.

To confirm what is going on, the feature should work like this: 
- It finds a code pattern for table driven tests
- It puts a breakpoint on the start of the for statement which iterates over the test table
- It skips the breakpoint n times where n is the index of the test
- On the n-th breakpoint hit it leaves the debugger in the current state, so that you could find out what's going on

Is it consistent wit your expectations?

I tested it on the following code:
```
func TestTable(t *testing.T) {
	tests := []struct{ a int }{
		{1}, {2}, {3},
	}
	for _, t := range tests {
		println(t.a)
	}
}
```
When I press on the debug for the last test, the test gets stopped with t.a equal to 3. (Could you check that it works this way in your case?)

If everything is consistent with your expectations, could you please share the structure of your tests so that I could understand what the code pattern you use is, and why it isn't handled correctly.

P.S. We have a discord community, feel fee to join: https://discord.com/invite/f9MHBXsVwr It's more interactive, so it helps resolve problems quicker.

**Comment by unguiculus** [comment]
I find it weird to learn that you handle this with breakpoints. Actually, I was wondering where this breakpoint always came from that I had never set myself. So, in fact, you do always run all tests in the table. It works with your example, but this is not how you do table-driven tests. The following example does not work:

```go
func TestTable(t *testing.T) {
	tests := []struct{ a int }{
		{1}, {2}, {3},
	}
	for _, tt := range tests {
		t.Run(fmt.Sprint(tt.a), func(t *testing.T) {
			println(tt.a)
		})
	}
}
```

**Comment by tooltitude-support** [comment]
Thanks for the example, I will take a look at it.

**Comment by tooltitude-support** [comment]
@unguiculus Have taken a look. It kind of works, however, if I put a breakpoint manually, it gets hit 6 times. Do I understand correctly that it actually hits twice for each value, once for t.Run, and once for the anonymous function?

**Comment by tooltitude-support** [comment]
@unguiculus 0.104.0 is out. Please check whether your use case now works. Please, reopen this issue if you still experience this problem.
